### ISSUE TITLE
Dependency issue with polymer.dart 1.0

### ISSUE THREAD

**Issue by vimalraj-a** [eredo/dartson#28]
Getting reflectable version mismatch. Please fix this.

pubspec.xml
```
name: 'GIS'
version: 0.0.1
description: GIS

environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  polymer: "^1.0.0-rc.2"
  polymer_elements: "^1.0.0-rc.1"
  route_hierarchical: "any"
  intl: "0.12.4+2"
  dartson: "0.2.4"
transformers:
- dartson
- polymer:
    entry_points: web/index.html
```

Error :
```
Working dir: P:\Workspaces\Workspace\GIS
C:\Dart\dart-sdk\bin\pub.bat get
Resolving dependencies...
Package reflectable has no versions that match >=0.3.1 <0.4.0 derived from:
- polymer 1.0.0-rc.2 depends on version ^0.3.1
- polymer_elements 1.0.0-rc.1 depends on version ^0.3.1
Process finished with exit code 1
```
