### ISSUE TITLE
subtype error

### ISSUE THREAD

**Issue by mnordine** [eredo/dartson#36]
I'm getting the following error when using the transformer:

```
Exception: type 'MyClass' is not a subtype of type 'StaticEntity' of 'clazz' where
  MyClass is from package:entities/src/entities_base.dart
  StaticEntity is from package:dartson/src/static_entity.dart

  Dartson.map	
  Dartson.decode	
  main	
```

**Comment by eredo** [comment]
Did you add the @Entity() annotation to your object classes which are serialized / deserialized?

**Comment by mnordine** [comment]
Yes, here's my entity:

```dart
import 'package:dartson/dartson.dart';

@Entity()
class MyClass
{
  int id;
}
```

**Comment by eredo** [comment]
How does your pubspec.yaml look like?

**Comment by mnordine** [comment]
It's there in the previous comment

**Comment by mnordine** [comment]
Also, here's the `pubspec.yaml` from the `entities` library:

```yaml
name: entities
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  dartson: any

dev_dependencies:
  test: '>=0.12.0 <0.13.0'

```
